<a href="https://colab.research.google.com/github/mina-fayazi/BN-Doped-Biphenylene/blob/main/BNDopedBiphenylene_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Mounting the Google Drive data:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
time: 5.06 s (started: 2023-08-10 21:26:44 +00:00)


In [16]:
!pip install ipython-autotime -q
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 7.56 s (started: 2023-08-10 21:26:51 +00:00)


In [17]:
import pandas as pd

# Defining the database directory:
data_path = "/content/drive/MyDrive/BNDopedBiphData/data/BNDopedBiphenylene.csv"
# Storing the dataset in a Pandas dataframe:
data_frame = pd.read_csv(data_path)
display(data_frame)

Atom Arrangements       a       b  \
0   1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5875  9.0995   
1   0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5876  9.1213   
2   0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5862  9.1222   
3   0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5874  9.0943   
4   0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5884  9.1184   
5   0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0....  7.5925  9.1151   
6   0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.0 0....  7.5962  9.0864   
7   0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.0 0....  7.5930  9.1117   
8   0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.0 0....  7.5888  9.1109   
9   0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.0 0....  7.5938  9.0797   
10  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 1....  7.5969  9.1049   
11  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5885  9.0929   
12  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5910  9.1183   
13  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5914  9.1176   
14  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5892  9.0961   
15  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5873  9.1203   
16  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5850  9.1246   
17  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5945  9.0905   
18  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5837  9.1255   
19  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5832  9.1139   
20  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.6014  9.0786   
21  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5870  9.1185   
22  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5813  9.1270   
23  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5801  9.1418   
24  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5693  9.1831   
25  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5691  9.1830   
26  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5781  9.1489   
27  0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5746  9.1522   
28  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5712  9.1546   
29  0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5707  9.1786   
30  0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5706  9.1792   
31  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737  9.1781   
32  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737  9.1781   
33  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5778  9.1463   
34  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5708  9.1784   

    Direct Eg  Indirect Eg  Epsilon_Real (Tangential)  \
0       0.000       0.0041                     3.1291   
1       0.000       0.0066                     3.1063   
2       0.000       0.0007                     2.9222   
3       0.000       0.0041                     2.7866   
4       0.000       0.0049                     2.7257   
5       0.000       0.0029                     3.7813   
6       0.000       0.0030                    14.5389   
7       0.106       0.0630                     4.1020   
8       0.000       0.0048                     4.0728   
9       0.083       0.0763                     4.6488   
10      0.105       0.0812                     3.7380   
11      0.000       0.0060                     6.4952   
12      0.000       0.0007                     2.4618   
13      0.000       0.0019                     3.3642   
14      0.000       0.0057                     3.2616   
15      0.000       0.0067                     3.1988   
16      0.000       0.0032                     2.4757   
17      0.000       0.0005                    10.2338   
18      0.000       0.0025                    15.3770   
19      0.088       0.0514                     5.1231   
20      0.071       0.0520                    18.3252   
21      0.101       0.0530                     5.1825   
22      0.000       0.0040                     3.7769   
23      0.000       0.0006             

time: 28.5 ms (started: 2023-08-10 21:27:01 +00:00)


In [18]:
import numpy as np

# Specifying the dataset size:
rows = 6
columns = 4

# Specifying x data:
x_data = []
for index, row in data_frame.iterrows():
    #print(index, '  ', row['Atom Arrangements'])
    atom_list = list(row['Atom Arrangements'].split())
    #print(atom_list)
    atom_float_list = [float(x) for x in atom_list]
    #print(atom_int_list)
    #atom_matrix = np.array(atom_float_list)
    atom_matrix = np.reshape(atom_float_list, (rows, columns))
    #print(atom_matrix)
    x_data.append(atom_matrix)
#x_data = np.stack(x_data, axis=0)
x_data = np.array(x_data)
#print(x_data)

time: 5.15 ms (started: 2023-08-10 21:27:10 +00:00)


In [19]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.optimizers import RMSprop

#Defining CNN model:
test_model = models.Sequential()
test_model.add(layers.Flatten())
test_model.add(layers.Dense(64, activation="relu"))
test_model.add(layers.Dense(40, activation="relu"))
test_model.add(layers.Dense(35, activation="relu"))
test_model.add(layers.Dense(1, "sigmoid"))

input_shape=(None, rows, columns, 1)
test_model.build(input_shape)

test_model.summary()

# Compiling the model:
test_model.compile(optimizer="RMSProp", loss="mean_squared_error", metrics=["accuracy"])

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 24)                0         
                                                                 
 dense_12 (Dense)            (None, 64)                1600      
                                                                 
 dense_13 (Dense)            (None, 40)                2600      
                                                                 
 dense_14 (Dense)            (None, 35)                1435      
                                                                 
 dense_15 (Dense)            (None, 1)                 36        
                                                                 
Total params: 5,671
Trainable params: 5,671
Non-trainable params: 0
_________________________________________________________________
time: 278 ms (started: 2023-08-10 21:27:17 +00:00)


In [20]:
# Importing math:
import math
# Importing MinMaxScaler from sklearn to normalize the data:
from sklearn.preprocessing import MinMaxScaler

# Creating the scaler:
y_scaler = MinMaxScaler()

# Defining variables:
batch_size = (len(data_frame) - 1) #number of training samples in one forward/backward pass
num_epoch = 5 #one epoch means one forward and one backward pass of all the training samples

# Getting headers of data_frame's columns:
df_headers = list(data_frame.columns)
y_headers = df_headers[1:] #slices the list

# Iterate over every column to define y_data:
for header in y_headers:
  print("The calculations for '{}' values:".format(header))
  y_data = np.array(data_frame[header])
  y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
  y_data = y_scaler.fit_transform(y_data)
  #print(header, y_data)

  actual_y = []
  predicted_y = []

  # Iterate over every row to define test and train data:
  for i in range(len(data_frame)):
    # Test:
    #print("Iteration ", i, " :")
    x_test = x_data[i]
    x_test = np.reshape(x_test, (1, rows, columns)) #Reshaping to 2D array
    y_test = y_data[i]
    y_test = np.reshape(y_test, (1, -1)) #Reshaping to 2D array
    actual_y.append(y_data[i])
    #print("x test shape: ", x_test.shape)
    #print("y test shape: ", y_test.shape)
    #print("x test: ", x_test)
    #print("y test: ", y_test)
    #print("----------------------------")
    # Train:
    x_train = np.delete(x_data, i, axis=0)
    y_train = np.delete(y_data, i, axis=0)
    #print("x train shape: ", x_train.shape)
    #print("y train shape: ", y_train.shape)
    #print("x train: ", x_train)
    #print("y train: ", y_train)

    # Model Training:
    model_log = test_model.fit(x_train, y_train,
                          batch_size=batch_size,
                          epochs=num_epoch,
                          verbose=1,
                          validation_data=(x_test, y_test))

    # Evaluating the model:
    test_model.evaluate(x_test, y_test, verbose=0)

    # Predicting the test data:
    y_pred = test_model.predict(x_test)
    predicted_y.append(y_pred)
    #print("Predicted y: ", y_pred, "   Predicted y without scalar: ",y_scaler.inverse_transform(y_pred))
    #print("Actual y:    ", y_test, "   Actual y without scaler:    ",y_scaler.inverse_transform(y_test))
    print(f"{'Predicted y:' : <20}{str(round(float(y_pred),4)) : <20}{'Predicted y without scalar:' : <30}{str(round(float(y_scaler.inverse_transform(y_pred)),4)) : <20}")
    print(f"{'Actual y:' : <20}{str(round(float(y_test),4)) : <20}{'Actual y without scaler:' : <30}{str(round(float(y_scaler.inverse_transform(y_test)),4)) : <20}")

  actual_y = np.reshape(actual_y, (-1))
  predicted_y = np.reshape(predicted_y, (-1))
  #print("Actual y values: ", actual_y)
  #print("Predicted y values: ", predicted_y)

  print('__________________________________________________')
  # Mean Squared Error:
  MSE = (np.square(np.subtract(actual_y, predicted_y))).mean()
  print("Mean Squared Error = ", MSE)
  # Root Mean Square Error:
  RMSE = math.sqrt(MSE)
  print("Root Mean Square Error = ", RMSE)

  # R-squared:
  ss_t = 0 #total sum of squares
  ss_r = 0 #total sum of square of residuals

  y_mean = actual_y.mean()
  #print(y_mean)

  for i in range(len(data_frame)):
    ss_t += (actual_y[i] - y_mean) ** 2
    ss_r += (actual_y[i] - predicted_y[i]) ** 2

  R2 = 1 - (ss_r/ss_t)
  print("R-Squared = ", R2)
  print('-----------------------------------------------------------------------------')

The calculations for 'a' values:
Epoch 1/5
1/1 [==============================] - 1s 1s/step - loss: 0.0832 - accuracy: 0.0294 - val_loss: 0.0021 - val_accuracy: 0.0000e+00
Epoch 2/5
1/1 [==============================] - 0s 81ms/step - loss: 0.0776 - accuracy: 0.0294 - val_loss: 0.0028 - val_accuracy: 0.0000e+00
Epoch 3/5
1/1 [==============================] - 0s 107ms/step - loss: 0.0747 - accuracy: 0.0588 - val_loss: 0.0019 - val_accuracy: 0.0000e+00
Epoch 4/5
1/1 [==============================] - 0s 80ms/step - loss: 0.0725 - accuracy: 0.0588 - val_loss: 0.0039 - val_accuracy: 0.0000e+00
Epoch 5/5
1/1 [==============================] - 0s 74ms/step
Predicted y:        0.519               Predicted y without scalar:   7.5859              
Actual y:           0.5697              Actual y without scaler:      7.5875              
Epoch 1/5
1/1 [==============================] - 0s 83ms/step - loss: 0.0690 - accuracy: 0.0588 - val_loss: 0.0041 - val_accuracy: 0.0000e+00
Epoch 2/5
1/1 

In [21]:
# Installing KerasTuner:
!pip install keras-tuner -q

time: 6.95 s (started: 2023-08-10 21:30:43 +00:00)


In [22]:
# Hyperparameter tuning using RandomSearch:

import keras_tuner
from keras.optimizers import Adam, SGD, RMSprop, Nadam

# Defining the search space for Hyperparameter tuning:
def build_model(hp):
  model = models.Sequential()
  model.add(layers.Flatten())
  # Tune the number of hidden layers:
  for i in range(hp.Int("num_layers", 1, 10)):
    model.add(
        layers.Dense(
            # Tune number of units separately.
            units=hp.Int(f"units_{i}", min_value=35, max_value=525, step=35),
            activation=hp.Choice("activation", ["relu", "selu", "sigmoid", "tanh"])))
  if hp.Boolean("dropout"):
    model.add(layers.Dropout(rate=0.25))
  # Output layer:
  model.add(layers.Dense(1, "sigmoid"))
  # Optimizer:
  learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2, sampling="log")
  optimizers_dict = {
      "Adam":    Adam(learning_rate=learning_rate),
      "SGD":     SGD(learning_rate=learning_rate),
      "RMSprop": RMSprop(learning_rate=learning_rate),
      "Nadam":   Nadam(learning_rate=learning_rate)
      }
  optimizer=hp.Choice("optimizer", values=["Adam", "SGD", "RMSprop", "Nadam"])
  model.compile(
      optimizer=optimizers_dict[optimizer],
      loss="mean_squared_error",
      metrics=["accuracy"]
      )

  return model

# Testing if the model builds successfully:
build_model(keras_tuner.HyperParameters())

time: 36.5 ms (started: 2023-08-10 21:30:54 +00:00)


In [23]:
# Initializing the tuner to start the search:
tuner = keras_tuner.RandomSearch(
  hypermodel=build_model,
  objective="val_accuracy",
  max_trials=20,
  executions_per_trial=10,
  overwrite=True,
  directory="/content/drive/MyDrive/BNDopedBiphData/finding_best_model",
  project_name="RSBestModel"
)

# Print a summary of the search space:
tuner.search_space_summary()

Search space summary
Default search space size: 6
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 10, 'step': 1, 'sampling': 'linear'}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 35, 'max_value': 525, 'step': 35, 'sampling': 'linear'}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'selu', 'sigmoid', 'tanh'], 'ordered': False}
dropout (Boolean)
{'default': False, 'conditions': []}
learning_rate (Float)
{'default': 0.0001, 'conditions': [], 'min_value': 0.0001, 'max_value': 0.01, 'step': None, 'sampling': 'log'}
optimizer (Choice)
{'default': 'Adam', 'conditions': [], 'values': ['Adam', 'SGD', 'RMSprop', 'Nadam'], 'ordered': False}
time: 89.7 ms (started: 2023-08-10 21:31:10 +00:00)


In [24]:
# Defining callbacks for tuning the number of epochs, and saving the Keras model in a checkpoint file:
my_callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss",
                                  patience=50 # Will stop training if the "val_loss" hasn't improved in 50 epochs
                                  ),
    keras.callbacks.ModelCheckpoint(filepath="/content/drive/MyDrive/BNDopedBiphData/checkpoint/model.{epoch:02d}-{val_accuracy:.2f}.h5",
                                    save_weights_only=True,
                                    monitor="val_accuracy",
                                    mode="max",
                                    save_best_only=True
                                    )
    ]

time: 852 µs (started: 2023-08-10 21:32:45 +00:00)


In [25]:
# Preparing the dataset:

import random
# Pick 5 random indexes for choosing test data:
random_list = random.sample(range(0, (len(data_frame)-1)), 15)

# Splitting X and Y data to test and train:
y_data = np.array(data_frame['Direct Eg'])
y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
y_data = y_scaler.fit_transform(y_data)
#print("x_data= \n", x_data, '\n', "y_data= \n", y_data, '\n')
x_test = []
y_test = []
for i in random_list:
  x_test = np.append(x_test, x_data[i])
  y_test = np.append(y_test, y_data[i])
x_test = np.reshape(x_test, (15, rows, columns)) #Reshaping to 2D array
y_test = np.reshape(y_test, (15, -1)) #Reshaping to 2D array
print("Indexes :", random_list, '\n', x_test, '\n', y_test)
x_train = np.delete(x_data, random_list, axis=0)
y_train = np.delete(y_data, random_list, axis=0)
#print(x_train, y_train)

Indexes : [4, 18, 12, 19, 15, 0, 31, 2, 5, 1, 9, 21, 30, 26, 27] 
 [[[0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 1. ]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 1.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 1.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]

In [26]:
# Start the search for the best hyperparameter configuration:

tuner.search(x_train, y_train, epochs=1000, callbacks=my_callbacks, validation_data=(x_test, y_test))

Trial 20 Complete [00h 10m 24s]
val_accuracy: 0.800000011920929

Best val_accuracy So Far: 0.800000011920929
Total elapsed time: 01h 23m 08s
time: 1h 23min 8s (started: 2023-08-10 21:34:04 +00:00)


In [27]:
# Get the top 2 models:

models = tuner.get_best_models(num_models=2)
best_model = models[0]
second_best_model = models[1]
# Build the best models:
best_model.build(input_shape)
best_model.summary()
second_best_model.build(input_shape)
second_best_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 24)                0         
                                                                 
 dense (Dense)               (None, 175)               4375      
                                                                 
 dense_1 (Dense)             (None, 35)                6160      
                                                                 
 dense_2 (Dense)             (None, 35)                1260      
                                                                 
 dense_3 (Dense)             (None, 1)                 36        
                                                                 
Total params: 11,831
Trainable params: 11,831
Non-trainable params: 0
_________________________________________________________________
Model: "sequential"
________________________________

In [28]:
# Print a summary of the search results:

tuner.results_summary()

Results summary
Results in /content/drive/MyDrive/BNDopedBiphData/finding_best_model/RSBestModel
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 00 summary
Hyperparameters:
num_layers: 3
units_0: 175
activation: tanh
dropout: False
learning_rate: 0.004543242153595538
optimizer: SGD
units_1: 35
units_2: 35
Score: 0.800000011920929

Trial 01 summary
Hyperparameters:
num_layers: 1
units_0: 385
activation: tanh
dropout: False
learning_rate: 0.0006318189784325001
optimizer: RMSprop
units_1: 420
units_2: 420
Score: 0.800000011920929

Trial 02 summary
Hyperparameters:
num_layers: 4
units_0: 70
activation: sigmoid
dropout: False
learning_rate: 0.000677305757021168
optimizer: RMSprop
units_1: 350
units_2: 175
units_3: 35
Score: 0.800000011920929

Trial 03 summary
Hyperparameters:
num_layers: 2
units_0: 210
activation: selu
dropout: False
learning_rate: 0.0043928238849566155
optimizer: Adam
units_1: 280
units_2: 175
units_3: 455
Score: 0.800000011920929

Trial 04 su