<a href="https://colab.research.google.com/github/mina-fayazi/BN-Doped-Biphenylene/blob/main/BNDopedBiphenylene_CNN_Optical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
# Mounting the Google Drive data:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [38]:
import pandas as pd

# Defining the database directory:
data_path = "/content/drive/MyDrive/BNDopedBiphData/data/BNDopedBiphenylene_Optical.csv"
# Storing the dataset in a Pandas dataframe:
data_frame = pd.read_csv(data_path)
display(data_frame)

Atom Arrangements  \
0  1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....   
1  0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....   
2  0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....   
3  0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....   
4  0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0....   

                                Optical (Tangential)  Optical (Vertical)  
0  0.3175 0.3522 0.3859 0.4181 0.4483 0.4762 0.50...                 NaN  
1  0.3474 0.4174 0.4942 0.5769 0.6642 0.7549 0.84...                 NaN  
2  0.2202 0.2556 0.2942 0.3357 0.3799 0.4261 0.47...                 NaN  
3  0.3179 0.3649 0.4132 0.4619 0.51 0.5567 0.6011...                 NaN  
4  0.3049 0.3541 0.4058 0.4593 0.5135 0.5675 0.62...                 NaN

In [39]:
import numpy as np

# Specifying the dataset size:
rows = 6
columns = 4

# Specifying x data:
x_data = []
for index, row in data_frame.iterrows():
    #print(index, '  ', row['Atom Arrangements'])
    atom_list = list(row['Atom Arrangements'].split())
    #print(atom_list)
    atom_float_list = [float(x) for x in atom_list]
    #print(atom_int_list)
    #atom_matrix = np.array(atom_float_list)
    atom_matrix = np.reshape(atom_float_list, (rows, columns))
    #print(atom_matrix)
    x_data.append(atom_matrix)
#x_data = np.stack(x_data, axis=0)
x_data = np.array(x_data)
print(x_data)
print(x_data.shape)

# Specifying x data:
y_data = []
for index, row in data_frame.iterrows():
    opt_list = list(row['Optical (Tangential)'].split())
    opt_float_list = [float(x) for x in opt_list]
    opt_matrix = np.array(opt_float_list)
    #print(opt_matrix)
    y_data.append(opt_matrix)

y_data = np.array(y_data)
print(y_data)
print(y_data.shape)

[[[1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 1.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 1.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 1. ]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]]
(5, 6, 4)
[[0.3175 0.3522 0.3859 0.4181 0.4483 0.4762 0.5017 0.5247 0.5455 0.5644
  0.5819 0.5986 0.615  0.6317 0.6491 0.6678 0.688  0.71   0.7336 0.7589
  0.7856 0.8132 0.8414 0.8694 0.8967 0.9227 0.9466 0.9678 0.9857 0.9999
  1.01   1.0155 1.0165 1.0127 1.0043 0.9913 0.9739 0.9526 0.9274 0.8989
  0.8674 0.8332 0.7968 0.7587 0.7192 0.6789 0.6381 0.5975 0.5575 0.5185
  0.4809 0.4452 0.41

In [40]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, models

#Definning CNN model:
model = models.Sequential()
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(24, activation='relu'))
model.add(layers.Dense(1))

input_shape=(None, rows, columns, 1)
model.build(input_shape)

model.summary()

# Compiling the model:
model.compile(loss="mean_squared_error", optimizer="RMSProp")

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 24)                0         
                                                                 
 dense_8 (Dense)             (None, 64)                1600      
                                                                 
 dense_9 (Dense)             (None, 32)                2080      
                                                                 
 dense_10 (Dense)            (None, 24)                792       
                                                                 
 dense_11 (Dense)            (None, 1)                 25        
                                                                 
Total params: 4,497
Trainable params: 4,497
Non-trainable params: 0
_________________________________________________________________


In [41]:
# Importing MinMaxScaler from sklearn to normalize the data:
from sklearn.preprocessing import MinMaxScaler

# Creating the scaler:
y_scaler = MinMaxScaler()

# Defining variables:
batch_size = (len(data_frame) - 1) #number of training samples in one forward/backward pass
num_epoch = 10 #one epoch means one forward and one backward pass of all the training samples

for i in range(5):
  y_array = np.reshape(y_data[i], (-1, 1)) #Reshaping 1D array to 2D array
  y_array = y_scaler.fit_transform(y_array)
  y_data[i] = np.reshape(y_array,-1)

print(y_data)

[[1.57628344e-01 1.99445650e-01 2.40057845e-01 2.78862376e-01
  3.15256688e-01 3.48879248e-01 3.79609544e-01 4.07327067e-01
  4.32393348e-01 4.55169920e-01 4.76259340e-01 4.96384671e-01
  5.16148470e-01 5.36273801e-01 5.57242709e-01 5.79778260e-01
  6.04121475e-01 6.30633888e-01 6.59074476e-01 6.89563750e-01
  7.21740178e-01 7.55001205e-01 7.88985298e-01 8.22728368e-01
  8.55627862e-01 8.86960713e-01 9.15762834e-01 9.41311159e-01
  9.62882622e-01 9.79995180e-01 9.92166787e-01 9.98794890e-01
  1.00000000e+00 9.95420583e-01 9.85297662e-01 9.69631236e-01
  9.48662328e-01 9.22993492e-01 8.92624729e-01 8.58279103e-01
  8.20318149e-01 7.79103398e-01 7.35237407e-01 6.89322728e-01
  6.41720897e-01 5.93154977e-01 5.43986503e-01 4.95059050e-01
  4.46854664e-01 3.99855387e-01 3.54543263e-01 3.11520848e-01
  2.71029164e-01 2.33550253e-01 1.99084117e-01 1.67751265e-01
  1.39792721e-01 1.14967462e-01 9.31549771e-02 7.43552663e-02
  5.82067968e-02 4.45890576e-02 3.32610268e-02 2.38611714e-02
  1.6389

In [42]:
actual_y = []

x_test = np.array(x_data[0])
x_test = np.reshape(x_test, (1, rows, columns)) #Reshaping to 2D array
y_test = np.array(y_data[0])
y_test = np.reshape(y_test, (1, -1)) #Reshaping to 2D array
actual_y.append(y_data[0])

print("x test shape: ", x_test.shape)
print("y test shape: ", y_test.shape)
print("x test: ", x_test)
print("y test: ", y_test)
print("----------------------------")
# Train:
x_train = np.delete(x_data, 0, axis=0)
y_train = np.delete(y_data, 0, axis=0)
print("x train shape: ", x_train.shape)
print("y train shape: ", y_train.shape)
print("x train: ", x_train)
print("y train: ", y_train)


x test shape:  (1, 6, 4)
y test shape:  (1, 101)
x test:  [[[1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]]
y test:  [[1.57628344e-01 1.99445650e-01 2.40057845e-01 2.78862376e-01
  3.15256688e-01 3.48879248e-01 3.79609544e-01 4.07327067e-01
  4.32393348e-01 4.55169920e-01 4.76259340e-01 4.96384671e-01
  5.16148470e-01 5.36273801e-01 5.57242709e-01 5.79778260e-01
  6.04121475e-01 6.30633888e-01 6.59074476e-01 6.89563750e-01
  7.21740178e-01 7.55001205e-01 7.88985298e-01 8.22728368e-01
  8.55627862e-01 8.86960713e-01 9.15762834e-01 9.41311159e-01
  9.62882622e-01 9.79995180e-01 9.92166787e-01 9.98794890e-01
  1.00000000e+00 9.95420583e-01 9.85297662e-01 9.69631236e-01
  9.48662328e-01 9.22993492e-01 8.92624729e-01 8.58279103e-01
  8.20318149e-01 7.79103398e-01 7.35237407e-01 6.89322728e-01
  6.41720897e-01 5.93154977e-01 5.43986503e-01 4.95059050e-01
  4.46854664e-01 3.99855387e-01 3.54543263e-01 3.11520848e-01
  2.7

In [43]:
predicted_y = []

# Model Training:
model_log = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=num_epoch,
                    verbose=0,
                    validation_data=(x_test, y_test))

# Evaluating the model:
model.evaluate(x_test, y_test, verbose=0)

# Predicting the test data:
y_pred = model.predict(x_test)
predicted_y.append(y_pred)

actual_y = np.reshape(actual_y, (-1))
predicted_y = np.reshape(predicted_y, (-1))
print("Actual y values: ", actual_y)
print("Predicted y values: ", predicted_y)


1/1 [==============================] - 0s 73ms/step
Actual y values:  [1.57628344e-01 1.99445650e-01 2.40057845e-01 2.78862376e-01
 3.15256688e-01 3.48879248e-01 3.79609544e-01 4.07327067e-01
 4.32393348e-01 4.55169920e-01 4.76259340e-01 4.96384671e-01
 5.16148470e-01 5.36273801e-01 5.57242709e-01 5.79778260e-01
 6.04121475e-01 6.30633888e-01 6.59074476e-01 6.89563750e-01
 7.21740178e-01 7.55001205e-01 7.88985298e-01 8.22728368e-01
 8.55627862e-01 8.86960713e-01 9.15762834e-01 9.41311159e-01
 9.62882622e-01 9.79995180e-01 9.92166787e-01 9.98794890e-01
 1.00000000e+00 9.95420583e-01 9.85297662e-01 9.69631236e-01
 9.48662328e-01 9.22993492e-01 8.92624729e-01 8.58279103e-01
 8.20318149e-01 7.79103398e-01 7.35237407e-01 6.89322728e-01
 6.41720897e-01 5.93154977e-01 5.43986503e-01 4.95059050e-01
 4.46854664e-01 3.99855387e-01 3.54543263e-01 3.11520848e-01
 2.71029164e-01 2.33550253e-01 1.99084117e-01 1.67751265e-01
 1.39792721e-01 1.14967462e-01 9.31549771e-02 7.43552663e-02
 5.82067968e-02