<a href="https://colab.research.google.com/github/mina-fayazi/BN-Doped-Biphenylene/blob/main/BNDopedBiphenylene_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mounting the Google Drive data:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install ipython-autotime -q
%load_ext autotime

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.7 MB/s eta 0:00:00
time: 284 µs (started: 2023-08-12 08:27:01 +00:00)


In [3]:
import pandas as pd

# Defining the database directory:
data_path = "/content/drive/MyDrive/BNDopedBiphData/data/BNDopedBiphenylene.csv"
# Storing the dataset in a Pandas dataframe:
data_frame = pd.read_csv(data_path)
display(data_frame)

Atom Arrangements       a       b  \
0   1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5875  9.0995   
1   0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5876  9.1213   
2   0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5862  9.1222   
3   0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5874  9.0943   
4   0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5884  9.1184   
5   0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0....  7.5925  9.1151   
6   0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.0 0....  7.5962  9.0864   
7   0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.0 0....  7.5930  9.1117   
8   0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.0 0....  7.5888  9.1109   
9   0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.0 0....  7.5938  9.0797   
10  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 1....  7.5969  9.1049   
11  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5885  9.0929   
12  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5910  9.1183   
13  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5914  9.1176   
14  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5892  9.0961   
15  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5873  9.1203   
16  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5850  9.1246   
17  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5945  9.0905   
18  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5837  9.1255   
19  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5832  9.1139   
20  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.6014  9.0786   
21  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5870  9.1185   
22  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5813  9.1270   
23  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5801  9.1418   
24  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5693  9.1831   
25  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5691  9.1830   
26  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5781  9.1489   
27  0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5746  9.1522   
28  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5712  9.1546   
29  0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5707  9.1786   
30  0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5706  9.1792   
31  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737  9.1781   
32  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737  9.1781   
33  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5778  9.1463   
34  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5708  9.1784   

    Direct Eg  Indirect Eg  Epsilon_Real (Tangential)  \
0       0.000       0.0041                     3.1291   
1       0.000       0.0066                     3.1063   
2       0.000       0.0007                     2.9222   
3       0.000       0.0041                     2.7866   
4       0.000       0.0049                     2.7257   
5       0.000       0.0029                     3.7813   
6       0.000       0.0030                    14.5389   
7       0.106       0.0630                     4.1020   
8       0.000       0.0048                     4.0728   
9       0.083       0.0763                     4.6488   
10      0.105       0.0812                     3.7380   
11      0.000       0.0060                     6.4952   
12      0.000       0.0007                     2.4618   
13      0.000       0.0019                     3.3642   
14      0.000       0.0057                     3.2616   
15      0.000       0.0067                     3.1988   
16      0.000       0.0032                     2.4757   
17      0.000       0.0005                    10.2338   
18      0.000       0.0025                    15.3770   
19      0.088       0.0514                     5.1231   
20      0.071       0.0520                    18.3252   
21      0.101       0.0530                     5.1825   
22      0.000       0.0040                     3.7769   
23      0.000       0.0006             

time: 674 ms (started: 2023-08-12 08:27:05 +00:00)


In [4]:
import numpy as np

# Specifying the dataset size:
rows = 6
columns = 4

# Specifying x data:
x_data = []
for index, row in data_frame.iterrows():
    #print(index, '  ', row['Atom Arrangements'])
    atom_list = list(row['Atom Arrangements'].split())
    #print(atom_list)
    atom_float_list = [float(x) for x in atom_list]
    #print(atom_int_list)
    #atom_matrix = np.array(atom_float_list)
    atom_matrix = np.reshape(atom_float_list, (rows, columns))
    #print(atom_matrix)
    x_data.append(atom_matrix)
#x_data = np.stack(x_data, axis=0)
x_data = np.array(x_data)
#print(x_data)

time: 11 ms (started: 2023-08-12 08:27:11 +00:00)


In [5]:
import tensorflow as tf
from tensorflow import keras
from keras import layers, models
from keras.optimizers import RMSprop

#Defining CNN model:
test_model = models.Sequential()
test_model.add(layers.Flatten())
test_model.add(layers.Dense(64, activation="relu"))
test_model.add(layers.Dense(40, activation="relu"))
test_model.add(layers.Dense(35, activation="relu"))
test_model.add(layers.Dense(1, "sigmoid"))

input_shape=(None, rows, columns, 1)
test_model.build(input_shape)

test_model.summary()

# Compiling the model:
test_model.compile(optimizer="RMSProp", loss="mean_squared_error", metrics=["accuracy"])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 24)                0         
                                                                 
 dense (Dense)               (None, 64)                1600      
                                                                 
 dense_1 (Dense)             (None, 40)                2600      
                                                                 
 dense_2 (Dense)             (None, 35)                1435      
                                                                 
 dense_3 (Dense)             (None, 1)                 36        
                                                                 
Total params: 5,671
Trainable params: 5,671
Non-trainable params: 0
_________________________________________________________________
time: 6.62 s (started: 2023-08-12 08:27:17 +00:00)


In [17]:
# Importing math:
import math
# Importing MinMaxScaler from sklearn to normalize the data:
from sklearn.preprocessing import MinMaxScaler

import sklearn.metrics

# Creating the scaler:
y_scaler = MinMaxScaler()

# Defining variables:
batch_size = (len(data_frame) - 1) #number of training samples in one forward/backward pass
num_epoch = 5 #one epoch means one forward and one backward pass of all the training samples

# Getting headers of data_frame's columns:
df_headers = list(data_frame.columns)
y_headers = df_headers[1:] #slices the list

# Iterate over every column to define y_data:
for header in y_headers:
  print("The calculations for '{}' values:".format(header))
  y_data = np.array(data_frame[header])
  #max_y_value = y_data.max()
  y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
  #y_data_scaled = y_data/max_y_value
  y_data = y_scaler.fit_transform(y_data)
  #print(header, y_data)

  actual_y = []
  predicted_y = []

  # Iterate over every row to define test and train data:
  for i in range(len(data_frame)):
    # Test:
    #print("Iteration ", i, " :")
    x_test = x_data[i]
    x_test = np.reshape(x_test, (1, rows, columns)) #Reshaping to 2D array
    y_test = y_data[i]
    y_test = np.reshape(y_test, (1, -1)) #Reshaping to 2D array
    actual_y.append(y_data[i])
    #print("x test shape: ", x_test.shape)
    #print("y test shape: ", y_test.shape)
    #print("x test: ", x_test)
    #print("y test: ", y_test)
    #print("----------------------------")
    # Train:
    x_train = np.delete(x_data, i, axis=0)
    y_train = np.delete(y_data, i, axis=0)
    #print("x train shape: ", x_train.shape)
    #print("y train shape: ", y_train.shape)
    #print("x train: ", x_train)
    #print("y train: ", y_train)

    # Model Training:
    model_log = test_model.fit(x_train, y_train,
                          batch_size=batch_size,
                          epochs=num_epoch,
                          verbose=0,
                          validation_data=(x_test, y_test))

    # Evaluating the model:
    test_model.evaluate(x_test, y_test, verbose=0)

    # Predicting the test data:
    y_pred = test_model.predict(x_test)
    predicted_y.append(y_pred)
    #print("Predicted y: ", y_pred, "   Predicted y without scalar: ",y_scaler.inverse_transform(y_pred))
    #print("Actual y:    ", y_test, "   Actual y without scaler:    ",y_scaler.inverse_transform(y_test))
    print(f"{'Predicted y:' : <20}{str(round(float(y_pred),4)) : <20}{'Predicted y without scaler:' : <30}{str(round(float(y_scaler.inverse_transform(y_pred)),4)) : <20}")
    print(f"{'Actual y:' : <20}{str(round(float(y_test),4)) : <20}{'Actual y without scaler:' : <30}{str(round(float(y_scaler.inverse_transform(y_test)),4)) : <20}")
    #print(f"{'Predicted y:' : <20}{str(round(float(y_pred),4)) : <20}{'Predicted y without scaler:' : <30}{str(round(float(max_y_value*y_pred),4)) : <20}")
    #print(f"{'Actual y:' : <20}{str(round(float(y_test),4)) : <20}{'Actual y without scaler:' : <30}{str(round(float(max_y_value*y_test),4)) : <20}")


  actual_y = np.reshape(actual_y, (-1))
  predicted_y = np.reshape(predicted_y, (-1))
  #print("Actual y values: ", actual_y)
  #print("Predicted y values: ", predicted_y)

  MSE = 0
  MSE_sk = 0
  RMSE = 0
  RMSE_sk = 0
  ss_t = 0 #total sum of squares
  ss_r = 0 #total sum of square of residuals

  print('__________________________________________________')
  # Mean Squared Error:
  MSE = (np.square(np.subtract(actual_y, predicted_y))).mean()
  print("Mean Squared Error = ", MSE)
  MSE_sk = sklearn.metrics.mean_squared_error(actual_y, predicted_y)
  print("MSE using sklearn = ", MSE_sk)
  # Root Mean Square Error:
  RMSE = math.sqrt(MSE)
  RMSE_sk = math.sqrt(MSE_sk)
  print("Root Mean Square Error = ", RMSE)
  print("RMSE using sklearn = ", RMSE_sk)

  # R-squared:
  y_mean = actual_y.mean()
  #print(y_mean)

  for i in range(len(data_frame)):
    ss_t += (actual_y[i] - y_mean) ** 2
    ss_r += (actual_y[i] - predicted_y[i]) ** 2

  R2 = 1 - (ss_r/ss_t)
  print("R-Squared = ", R2)
  print("R-squared using sklearn = ", sklearn.metrics.r2_score(actual_y, predicted_y))
  print('-----------------------------------------------------------------------------')

The calculations for 'a' values:
1/1 [==============================] - 0s 25ms/step
Predicted y:        0.6556              Predicted y without scaler:   7.5903              
Actual y:           0.5697              Actual y without scaler:      7.5875              
1/1 [==============================] - 0s 19ms/step
Predicted y:        0.7068              Predicted y without scaler:   7.5919              
Actual y:           0.5728              Actual y without scaler:      7.5876              
1/1 [==============================] - 0s 16ms/step
Predicted y:        0.5515              Predicted y without scaler:   7.5869              
Actual y:           0.5294              Actual y without scaler:      7.5862              
1/1 [==============================] - 0s 15ms/step
Predicted y:        0.7572              Predicted y without scaler:   7.5936              
Actual y:           0.5666              Actual y without scaler:      7.5874              
1/1 [==========================

In [8]:
# Installing KerasTuner:
!pip install keras-tuner -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 4.4 MB/s eta 0:00:00
time: 3.72 s (started: 2023-08-12 08:31:42 +00:00)


In [9]:
# Hyperparameter tuning using RandomSearch:

import keras_tuner
from keras.optimizers import Adam, SGD, RMSprop, Nadam

# Defining the search space for Hyperparameter tuning:
def build_model(hp):
  model = models.Sequential()
  model.add(layers.Flatten())
  # Tune the number of hidden layers:
  for i in range(hp.Int("num_layers", 1, 10)):
    model.add(
        layers.Dense(
            # Tune number of units separately.
            units=hp.Int(f"units_{i}", min_value=35, max_value=525, step=35),
            activation=hp.Choice("activation", ["relu", "selu", "sigmoid", "tanh"])))
  if hp.Boolean("dropout"):
    model.add(layers.Dropout(rate=0.25))
  # Output layer:
  model.add(layers.Dense(1, "sigmoid"))
  # Optimizer:
  learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2, sampling="log")
  optimizers_dict = {
      "Adam":    Adam(learning_rate=learning_rate),
      "SGD":     SGD(learning_rate=learning_rate),
      "RMSprop": RMSprop(learning_rate=learning_rate),
      "Nadam":   Nadam(learning_rate=learning_rate)
      }
  optimizer=hp.Choice("optimizer", values=["Adam", "SGD", "RMSprop", "Nadam"])
  model.compile(
      optimizer=optimizers_dict[optimizer],
      loss="mean_squared_error",
      metrics=["accuracy"]
      )

  return model

# Testing if the model builds successfully:
build_model(keras_tuner.HyperParameters())

time: 212 ms (started: 2023-08-12 08:31:49 +00:00)


In [10]:
# Initializing the tuner to start the search:
tuner = keras_tuner.RandomSearch(
  hypermodel=build_model,
  objective="val_accuracy",
  max_trials=20,
  executions_per_trial=10,
  overwrite=True,
  directory="/content/drive/MyDrive/BNDopedBiphData/finding_best_model",
  project_name="RSBestModel"
)

# Print a summary of the search space:
tuner.search_space_summary()

Search space summary
Default search space size: 6
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 1, 'max_value': 10, 'step': 1, 'sampling': 'linear'}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 35, 'max_value': 525, 'step': 35, 'sampling': 'linear'}
activation (Choice)
{'default': 'relu', 'conditions': [], 'values': ['relu', 'selu', 'sigmoid', 'tanh'], 'ordered': False}
dropout (Boolean)
{'default': False, 'conditions': []}
learning_rate (Float)
{'default': 0.0001, 'conditions': [], 'min_value': 0.0001, 'max_value': 0.01, 'step': None, 'sampling': 'log'}
optimizer (Choice)
{'default': 'Adam', 'conditions': [], 'values': ['Adam', 'SGD', 'RMSprop', 'Nadam'], 'ordered': False}
time: 1.07 s (started: 2023-08-12 08:31:58 +00:00)


In [11]:
# Defining callbacks for tuning the number of epochs, and saving the Keras model in a checkpoint file:
my_callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_accuracy",
                                  mode="max",
                                  baseline=0.9,
                                  patience=100, # Will stop training if the "val_accuracy" hasn't improved in 100 epochs
                                  start_from_epoch=20
                                  ),
    keras.callbacks.ModelCheckpoint(filepath="/content/drive/MyDrive/BNDopedBiphData/checkpoint/model.{epoch:02d}-{val_accuracy:.2f}.h5",
                                    save_weights_only=True,
                                    monitor="val_accuracy",
                                    mode="max",
                                    save_best_only=True
                                    )
    ]

time: 424 µs (started: 2023-08-12 08:32:08 +00:00)


In [12]:
# Preparing the dataset:

import random
# Pick 5 random indexes for choosing test data:
random_list = random.sample(range(0, (len(data_frame)-1)), 5)

# Splitting X and Y data to test and train:
y_data = np.array(data_frame['Direct Eg'])
#max_y_value = y_data.max()
y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
#y_data_scaled = y_data/max_y_value
y_data = y_scaler.fit_transform(y_data)
#print("x_data= \n", x_data, '\n', "y_data= \n", y_data, '\n')
x_test = []
y_test = []
for i in random_list:
  x_test = np.append(x_test, x_data[i])
  y_test = np.append(y_test, y_data[i])
x_test = np.reshape(x_test, (5, rows, columns)) #Reshaping to 2D array
y_test = np.reshape(y_test, (5, -1)) #Reshaping to 2D array
print("Indexes :", random_list, '\n', x_test, '\n', y_test)
x_train = np.delete(x_data, random_list, axis=0)
y_train = np.delete(y_data, random_list, axis=0)
#print(x_train, y_train)

Indexes : [11, 20, 24, 4, 12] 
 [[[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 1.  0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 1. ]]

 [[0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 1.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]] 
 [[0.        ]
 [0.66981132]
 [0.        ]
 [0.        ]
 [0.        ]]
time: 6.03 ms (started: 2023-08-12 08:32:30 +00:00)


In [13]:
# Start the search for the best hyperparameter configuration:

tuner.search(x_train, y_train, epochs=1000, callbacks=my_callbacks, validation_data=(x_test, y_test))

Trial 20 Complete [00h 01m 35s]
val_accuracy: 0.720000010728836

Best val_accuracy So Far: 0.800000011920929
Total elapsed time: 00h 29m 21s
time: 29min 21s (started: 2023-08-12 08:32:40 +00:00)


In [14]:
# Get the top 2 models:

models = tuner.get_best_models(num_models=2)
best_model = models[0]
second_best_model = models[1]
# Build the best models:
best_model.build(input_shape)
best_model.summary()
second_best_model.build(input_shape)
second_best_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 24)                0         
                                                                 
 dense (Dense)               (None, 70)                1750      
                                                                 
 dense_1 (Dense)             (None, 35)                2485      
                                                                 
 dense_2 (Dense)             (None, 35)                1260      
                                                                 
 dense_3 (Dense)             (None, 35)                1260      
                                                                 
 dense_4 (Dense)             (None, 35)                1260      
                                                                 
 dropout (Dropout)           (None, 35)                0

In [15]:
# Print a summary of the search results:

tuner.results_summary()

Results summary
Results in /content/drive/MyDrive/BNDopedBiphData/finding_best_model/RSBestModel
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 00 summary
Hyperparameters:
num_layers: 5
units_0: 70
activation: tanh
dropout: True
learning_rate: 0.0003224373107912853
optimizer: Adam
units_1: 35
units_2: 35
units_3: 35
units_4: 35
Score: 0.800000011920929

Trial 01 summary
Hyperparameters:
num_layers: 10
units_0: 210
activation: relu
dropout: True
learning_rate: 0.0009224369746841877
optimizer: Nadam
units_1: 490
units_2: 315
units_3: 350
units_4: 175
units_5: 35
units_6: 35
units_7: 35
units_8: 35
units_9: 35
Score: 0.800000011920929

Trial 02 summary
Hyperparameters:
num_layers: 6
units_0: 315
activation: relu
dropout: True
learning_rate: 0.0003838912108737987
optimizer: Adam
units_1: 105
units_2: 490
units_3: 525
units_4: 105
units_5: 245
units_6: 315
units_7: 210
units_8: 490
units_9: 455
Score: 0.800000011920929

Trial 03 summary
Hyperparameters:
num_la

In [18]:
# Retrain dataset with the best model:

# Iterate over every column to define y_data:
for header in y_headers:
  print("The calculations for '{}' values:".format(header))
  y_data = np.array(data_frame[header])
  #max_y_value = y_data.max()
  y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
  #y_data_scaled = y_data/max_y_value
  y_data = y_scaler.fit_transform(y_data)
  #print(header, y_data)

  actual_y = []
  predicted_y = []

  # Iterate over every row to define test and train data:
  for i in range(len(data_frame)):
    # Test:
    #print("Iteration ", i, " :")
    x_test = x_data[i]
    x_test = np.reshape(x_test, (1, rows, columns)) #Reshaping to 2D array
    y_test = y_data[i]
    y_test = np.reshape(y_test, (1, -1)) #Reshaping to 2D array
    actual_y.append(y_data[i])
    #print("x test shape: ", x_test.shape)
    #print("y test shape: ", y_test.shape)
    #print("x test: ", x_test)
    #print("y test: ", y_test)
    #print("----------------------------")
    # Train:
    x_train = np.delete(x_data, i, axis=0)
    y_train = np.delete(y_data, i, axis=0)
    #print("x train shape: ", x_train.shape)
    #print("y train shape: ", y_train.shape)
    #print("x train: ", x_train)
    #print("y train: ", y_train)

    # Model Training:
    history = best_model.fit(x_train, y_train,
                             batch_size=batch_size,
                             epochs=1000,
                             callbacks=my_callbacks,
                             verbose=0,
                             validation_data=(x_test, y_test))

    print("Number of epochs: ", len(history.history['val_accuracy']), '\n')

    # Evaluating the model:
    best_model.evaluate(x_test, y_test, verbose=0)

    # Predicting the test data:
    y_pred = best_model.predict(x_test)
    predicted_y.append(y_pred)
    #print("Predicted y: ", y_pred, "   Predicted y without scalar: ",y_scaler.inverse_transform(y_pred))
    #print("Actual y:    ", y_test, "   Actual y without scaler:    ",y_scaler.inverse_transform(y_test))
    print(f"{'Predicted y:' : <20}{str(round(float(y_pred),4)) : <20}{'Predicted y without scaler:' : <30}{str(round(float(y_scaler.inverse_transform(y_pred)),4)) : <20}")
    print(f"{'Actual y:' : <20}{str(round(float(y_test),4)) : <20}{'Actual y without scaler:' : <30}{str(round(float(y_scaler.inverse_transform(y_test)),4)) : <20}")
    #print(f"{'Predicted y:' : <20}{str(round(float(y_pred),4)) : <20}{'Predicted y without scaler:' : <30}{str(round(float(max_y_value*y_pred),4)) : <20}")
    #print(f"{'Actual y:' : <20}{str(round(float(y_test),4)) : <20}{'Actual y without scaler:' : <30}{str(round(float(max_y_value*y_test),4)) : <20}")

  actual_y = np.reshape(actual_y, (-1))
  predicted_y = np.reshape(predicted_y, (-1))
  #print("Actual y values: ", actual_y)
  #print("Predicted y values: ", predicted_y)

  MSE = 0
  RMSE = 0
  ss_t = 0 #total sum of squares
  ss_r = 0 #total sum of square of residuals

  print('__________________________________________________')
  # Mean Squared Error:
  MSE = (np.square(np.subtract(actual_y, predicted_y))).mean()
  print("Mean Squared Error = ", MSE)
  # Root Mean Square Error:
  RMSE = math.sqrt(MSE)
  print("Root Mean Square Error = ", RMSE)

  # R-squared:
  y_mean = actual_y.mean()
  #print(y_mean)

  for i in range(len(data_frame)):
    ss_t += (actual_y[i] - y_mean) ** 2
    ss_r += (actual_y[i] - predicted_y[i]) ** 2

  R2 = 1 - (ss_r/ss_t)
  print("R-Squared = ", R2)
  print('-----------------------------------------------------------------------------')

The calculations for 'a' values:
Number of epochs:  120 

1/1 [==============================] - 0s 20ms/step
Predicted y:        0.607               Predicted y without scaler:   7.5887              
Actual y:           0.5697              Actual y without scaler:      7.5875              
Number of epochs:  120 

1/1 [==============================] - 0s 15ms/step
Predicted y:        0.6068              Predicted y without scaler:   7.5887              
Actual y:           0.5728              Actual y without scaler:      7.5876              
Number of epochs:  120 

1/1 [==============================] - 0s 17ms/step
Predicted y:        0.5246              Predicted y without scaler:   7.586               
Actual y:           0.5294              Actual y without scaler:      7.5862              
Number of epochs:  120 

1/1 [==============================] - 0s 18ms/step
Predicted y:        0.5702              Predicted y without scaler:   7.5875              
Actual y:           0.