<a href="https://colab.research.google.com/github/mina-fayazi/BN-Doped-Biphenylene/blob/main/BNDopedBiphenylene_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
# Mounting the Google Drive data:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [58]:
# Importing libraries and packages:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models

In [51]:
# Defining the database directory:
data_path = "/content/drive/MyDrive/BNDopedBiphData/data/BNDopedBiphenylene.csv"
# Storing the dataset in a Pandas dataframe:
data_frame = pd.read_csv(data_path)
display(data_frame)

Batch Number                                  Atom Arrangements       a  \
0              1  1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5875   
1              2  0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5876   
2              3  0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5862   
3              4  0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5874   
4              5  0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5884   
5              6  0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0....  7.5925   
6              7  0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.0 0....  7.5962   
7              8  0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.0 0....  7.5930   
8              9  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.5 0.0 0....  7.5888   
9             10  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.0 0.0 0....  7.5938   
10            11  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 1....  7.5969   
11            12  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5885   
12            13  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5910   
13            14  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5914   
14            15  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5892   
15            16  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5873   
16            17  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5850   
17            18  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5945   
18            19  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5837   
19            20  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5832   
20            21  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.6014   
21            22  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5870   
22            23  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0....  7.5813   
23            24  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5801   
24            25  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5693   
25            26  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5691   
26            27  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5781   
27            28  0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5746   
28            29  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5712   
29            30  0.5 0.5 0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5707   
30            31  0.5 0.5 1.0 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5706   
31            32  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737   
32            33  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.0 0.5 0....  7.5737   

         b  Direct Eg  Indirect Eg  Optical Properties  
0   9.0995      0.000       0.0041                 NaN  
1   9.1213      0.000       0.0066                 NaN  
2   9.1222      0.000       0.0007                 NaN  
3   9.0943      0.000       0.0041                 NaN  
4   9.1184      0.000       0.0049                 NaN  
5   9.1151      0.000       0.0029                 NaN  
6   9.0864      0.000       0.0030                 NaN  
7   9.1117      0.106       0.0630                 NaN  
8   9.1109      0.000       0.0048                 NaN  
9   9.0797      0.083       0.0763                 NaN  
10  9.1049      0.105       0.0812                 NaN  
11  9.0929      0.000       0.0060                 NaN  
12  9.1183      0.000       0.0007                 NaN  
13  9.1176      0.000       0.0019                 NaN  
14  9.0961      0.000       0.0057                 NaN  
15  9.1203      0.000       0.0067                 NaN  
16  9.1246      0.000       0.0032                 NaN  
17  9.0905      0.000       0.0005                 NaN  
18  9.1255      0.000       0.0025                 NaN  
19  9.1139      0.088       0.0514                 NaN  
20  9.0786      0.071       0.0520                 NaN  
21  9.1185      0.101       0.0530                 NaN  
22  9.

In [93]:
# Importing MinMaxScaler from sklearn to normalize the data:
from sklearn.preprocessing import MinMaxScaler

# Creating the scaler:
y_scaler = MinMaxScaler()

# Specifying the dataset size:
rows = 6
columns = 4

# Specifying x and y data:
x_data = []
for index, row in data_frame.iterrows():
    #print(index, '  ', row['Atom Arrangements'])
    atom_list = list(row['Atom Arrangements'].split())
    #print(atom_list)
    atom_float_list = [float(x) for x in atom_list]
    #print(atom_int_list)
    #atom_matrix = np.array(atom_float_list)
    atom_matrix = np.reshape(atom_float_list, (rows, columns))
    #print(atom_matrix)
    x_data.append(atom_matrix)
#x_data = np.stack(x_data, axis=0)
#print(x_data)

y_data = np.array(data_frame['a'])
#y_data = data_frame['a'].values.tolist()
y_data = np.reshape(y_data, (-1, 1)) #Reshaping 1D array to 2D array
y_data = y_scaler.fit_transform(y_data)
#y_data = np.reshape(y_data, (-1,-1,1)) #Reshaping 2D array to 3D array
#print(y_data)

In [95]:
# Loading the train and test data:
# Test:
x_test = np.array(x_data[0])
x_test = np.reshape(x_test, (1, rows, columns)) #Reshaping to 2D array
#x_test = np.reshape(x_test, (1, -1)) #Reshaping to 2D array
y_test = np.array(y_data[0])
y_test = np.reshape(y_test, (1, -1)) #Reshaping to 2D array
print("x test shape: ", x_test.shape)
print("y test shape: ", y_test.shape)
print("x test: ", x_test)
print("y test: ", y_test)
print("----------------------------")
# Train:
x_train = np.delete(x_data, 0, axis=0)
y_train = np.delete(y_data, 0, axis=0)
print("x train shape: ", x_train.shape)
print("y train shape: ", y_train.shape)
print("x train: ", x_train)
print("y train: ", y_train)

x test shape:  (1, 6, 4)
y test shape:  (1, 1)
x test:  [[[1.  0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]]
y test:  [[0.56965944]]
----------------------------
x train shape:  (32, 6, 4)
y train shape:  (32, 1)
x train:  [[[0.5 1.  0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 1.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 1. ]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [1.  0.5 0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 1.  0.5 0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5]]

 [[0.5 0.5 0.5 0.5]
  [0.5 0.5 1.  0.5]
  [0.5 0.5 0.  0.5]
  [0.5 0.5 0.5 0.5]
  [0.5 0.5 0.5 0.5

In [101]:
#Definning CNN model:
model = models.Sequential()
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(24, activation='relu'))
model.add(layers.Dense(1))

input_shape=(None, rows, columns, 1)
model.build(input_shape)

model.summary()

Model: "sequential_35"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 24)                0         
                                                                 
 dense_107 (Dense)           (None, 64)                1600      
                                                                 
 dense_108 (Dense)           (None, 32)                2080      
                                                                 
 dense_109 (Dense)           (None, 24)                792       
                                                                 
 dense_110 (Dense)           (None, 1)                 25        
                                                                 
Total params: 4,497
Trainable params: 4,497
Non-trainable params: 0
_________________________________________________________________


In [102]:
# Compiling the model:
model.compile(loss="mean_squared_error", optimizer="RMSProp")

batch_size = 32 #number of training samples in one forward/backward pass
num_epoch = 10 #one epoch means one forward and one backward pass of all the training samples

# Model Training:
model_log = model.fit(x_train, y_train,
                      batch_size=batch_size,
                      epochs=num_epoch,
                      verbose=1,
                      validation_data=(x_test, y_test))

Epoch 1/10
1/1 [==============================] - 1s 535ms/step - loss: 0.1375 - val_loss: 0.0074
Epoch 2/10
1/1 [==============================] - 0s 33ms/step - loss: 0.0774 - val_loss: 0.0065
Epoch 3/10
1/1 [==============================] - 0s 34ms/step - loss: 0.0649 - val_loss: 0.0018
Epoch 4/10
1/1 [==============================] - 0s 32ms/step - loss: 0.0576 - val_loss: 0.0020
Epoch 5/10
1/1 [==============================] - 0s 34ms/step - loss: 0.0523 - val_loss: 6.8937e-05
Epoch 6/10
1/1 [==============================] - 0s 37ms/step - loss: 0.0472 - val_loss: 5.5412e-04
Epoch 7/10
1/1 [==============================] - 0s 54ms/step - loss: 0.0432 - val_loss: 4.7435e-04
Epoch 8/10
1/1 [==============================] - 0s 44ms/step - loss: 0.0394 - val_loss: 2.1152e-04
Epoch 9/10
1/1 [==============================] - 0s 40ms/step - loss: 0.0359 - val_loss: 0.0039
Epoch 10/10
1/1 [==============================] - 0s 32ms/step - loss: 0.0318 - val_loss: 4.7542e-05


In [113]:
# Evaluating the model:
model.evaluate(x_test, y_test, verbose=1)

1/1 [==============================] - 0s 29ms/step - loss: 4.7542e-05


4.75419255963061e-05

In [117]:
model.evaluate(x_test, y_test)

y_pred = model.predict(x_test)
print("Predicted y: ", y_pred, "   Predicted y without scalar: ",y_scaler.inverse_transform(y_pred))
print("Actual y:    ", y_test, "   Actual y without scaler:    ",y_scaler.inverse_transform(y_test))

1/1 [==============================] - 0s 19ms/step
Predicted y:  [[0.57655454]]    Predicted y without scalar:  [[7.587723]]
Actual y:     [[0.56965944]]    Actual y without scaler:     [[7.5875]]
